
  
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu
    mode: 777
    owner: ubuntu
    group: ubuntu
hooks:
  BeforInstall:
    - location: fix_previleges.sh
      timeout: 50
      runas: root
  AfterInstall:
    - location: installapp.sh
      timeout: 50
      runas: root
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 50
      runas: root
