
  
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: installapp
      timeout: 50
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 50
