
  
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  AfterInstall:
    - location: installapp.sh
      timeout: 100
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 100
