version: 0.2

phases:
  install:
    commands:
      - echo In install phase
      - sudo apt install python -y
  pre_build:
    commands:
      - echo in the pre_build phase...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - python app.py
  post_build:
    commands:
      - echo Build completed on `date`
