version: 0.2

phases:
  install:
    commands:
      - echo In install phase
      - sudo apt update
      - sudo apt install software-properties-common
      - sudo add-apt-repository ppa:deadsnakes/ppa
      - sudo apt update
      - sudo apt install python3 -y
      - sudo apt install python3-pip
  pre_build:
    commands:
      - echo in the pre_build phase...
      - pip3 install -r requirements.txt
#   build:
#     commands:
#       - echo Build started on `date`
#   post_build:
#     commands:
#       - echo Build completed on `date`
# artifacts:
#   type: zip
#   files: 
#   paths:
#     - '*'
